# Generated by Django 5.0.1 on 2024-01-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int1', models.IntegerField()),
                ('int2', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('str1', models.CharField(max_length=255)),
                ('str2', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
